/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BaremeRouteImport } from './routes/bareme'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as PhotoRouteImport } from './routes/photo'
import { Route as QuetesRouteImport } from './routes/quetes'
import { Route as SimulateurRouteImport } from './routes/simulateur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaremeRoute = BaremeRouteImport.update({
  id: '/bareme',
  path: '/bareme',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoRoute = PhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuetesRoute = QuetesRouteImport.update({
  id: '/quetes',
  path: '/quetes',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bareme': typeof BaremeRoute
  '/codex': typeof CodexRoute
  '/lore': typeof LoreRoute
  '/photo': typeof PhotoRoute
  '/quetes': typeof QuetesRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bareme': typeof BaremeRoute
  '/codex': typeof CodexRoute
  '/lore': typeof LoreRoute
  '/photo': typeof PhotoRoute
  '/quetes': typeof QuetesRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bareme': typeof BaremeRoute
  '/codex': typeof CodexRoute
  '/lore': typeof LoreRoute
  '/photo': typeof PhotoRoute
  '/quetes': typeof QuetesRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bareme' | '/codex' | '/lore' | '/photo' | '/quetes' | '/simulateur'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/bareme' | '/codex' | '/lore' | '/photo' | '/quetes' | '/simulateur'
  id:
    | '__root__'
    | '/'
    | '/bareme'
    | '/codex'
    | '/lore'
    | '/photo'
    | '/quetes'
    | '/simulateur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaremeRoute: typeof BaremeRoute
  CodexRoute: typeof CodexRoute
  LoreRoute: typeof LoreRoute
  PhotoRoute: typeof PhotoRoute
  QuetesRoute: typeof QuetesRoute
  SimulateurRoute: typeof SimulateurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bareme': {
      id: '/bareme'
      path: '/bareme'
      fullPath: '/bareme'
      preLoaderRoute: typeof BaremeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo': {
      id: '/photo'
      path: '/photo'
      fullPath: '/photo'
      preLoaderRoute: typeof PhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quetes': {
      id: '/quetes'
      path: '/quetes'
      fullPath: '/quetes'
      preLoaderRoute: typeof QuetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaremeRoute: BaremeRoute,
  CodexRoute: CodexRoute,
  LoreRoute: LoreRoute,
  PhotoRoute: PhotoRoute,
  QuetesRoute: QuetesRoute,
  SimulateurRoute: SimulateurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
