/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BaremeRouteImport } from './routes/bareme'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as PhotoRouteImport } from './routes/photo'
import { Route as QuetesRouteImport } from './routes/quetes'
import { Route as SimulateurRouteImport } from './routes/simulateur'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminJuryRouteImport } from './routes/admin.jury'
import { Route as AdminMissionsRouteImport } from './routes/admin.missions'
import { Route as AdminRelevesRouteImport } from './routes/admin.releves'
import { Route as AdminRunRouteImport } from './routes/admin.run'
import { Route as AdminSupervisionRouteImport } from './routes/admin.supervision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BaremeRoute = BaremeRouteImport.update({
  id: '/bareme',
  path: '/bareme',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoRoute = PhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuetesRoute = QuetesRouteImport.update({
  id: '/quetes',
  path: '/quetes',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJuryRoute = AdminJuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsRoute = AdminMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelevesRoute = AdminRelevesRouteImport.update({
  id: '/releves',
  path: '/releves',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRunRoute = AdminRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupervisionRoute = AdminSupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bareme': typeof BaremeRoute
  '/codex': typeof CodexRoute
  '/connexion': typeof ConnexionRoute
  '/lore': typeof LoreRoute
  '/photo': typeof PhotoRoute
  '/quetes': typeof QuetesRoute
  '/simulateur': typeof SimulateurRoute
  '/admin/jury': typeof AdminJuryRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/releves': typeof AdminRelevesRoute
  '/admin/run': typeof AdminRunRoute
  '/admin/supervision': typeof AdminSupervisionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bareme': typeof BaremeRoute
  '/codex': typeof CodexRoute
  '/connexion': typeof ConnexionRoute
  '/lore': typeof LoreRoute
  '/photo': typeof PhotoRoute
  '/quetes': typeof QuetesRoute
  '/simulateur': typeof SimulateurRoute
  '/admin/jury': typeof AdminJuryRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/releves': typeof AdminRelevesRoute
  '/admin/run': typeof AdminRunRoute
  '/admin/supervision': typeof AdminSupervisionRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bareme': typeof BaremeRoute
  '/codex': typeof CodexRoute
  '/connexion': typeof ConnexionRoute
  '/lore': typeof LoreRoute
  '/photo': typeof PhotoRoute
  '/quetes': typeof QuetesRoute
  '/simulateur': typeof SimulateurRoute
  '/admin/jury': typeof AdminJuryRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/releves': typeof AdminRelevesRoute
  '/admin/run': typeof AdminRunRoute
  '/admin/supervision': typeof AdminSupervisionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bareme'
    | '/codex'
    | '/connexion'
    | '/lore'
    | '/photo'
    | '/quetes'
    | '/simulateur'
    | '/admin/jury'
    | '/admin/missions'
    | '/admin/releves'
    | '/admin/run'
    | '/admin/supervision'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bareme'
    | '/codex'
    | '/connexion'
    | '/lore'
    | '/photo'
    | '/quetes'
    | '/simulateur'
    | '/admin/jury'
    | '/admin/missions'
    | '/admin/releves'
    | '/admin/run'
    | '/admin/supervision'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bareme'
    | '/codex'
    | '/connexion'
    | '/lore'
    | '/photo'
    | '/quetes'
    | '/simulateur'
    | '/admin/jury'
    | '/admin/missions'
    | '/admin/releves'
    | '/admin/run'
    | '/admin/supervision'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BaremeRoute: typeof BaremeRoute
  CodexRoute: typeof CodexRoute
  ConnexionRoute: typeof ConnexionRoute
  LoreRoute: typeof LoreRoute
  PhotoRoute: typeof PhotoRoute
  QuetesRoute: typeof QuetesRoute
  SimulateurRoute: typeof SimulateurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bareme': {
      id: '/bareme'
      path: '/bareme'
      fullPath: '/bareme'
      preLoaderRoute: typeof BaremeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo': {
      id: '/photo'
      path: '/photo'
      fullPath: '/photo'
      preLoaderRoute: typeof PhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quetes': {
      id: '/quetes'
      path: '/quetes'
      fullPath: '/quetes'
      preLoaderRoute: typeof QuetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jury': {
      id: '/admin/jury'
      path: '/jury'
      fullPath: '/admin/jury'
      preLoaderRoute: typeof AdminJuryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions': {
      id: '/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AdminMissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/releves': {
      id: '/admin/releves'
      path: '/releves'
      fullPath: '/admin/releves'
      preLoaderRoute: typeof AdminRelevesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/run': {
      id: '/admin/run'
      path: '/run'
      fullPath: '/admin/run'
      preLoaderRoute: typeof AdminRunRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supervision': {
      id: '/admin/supervision'
      path: '/supervision'
      fullPath: '/admin/supervision'
      preLoaderRoute: typeof AdminSupervisionRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminJuryRoute: typeof AdminJuryRoute
  AdminMissionsRoute: typeof AdminMissionsRoute
  AdminRelevesRoute: typeof AdminRelevesRoute
  AdminRunRoute: typeof AdminRunRoute
  AdminSupervisionRoute: typeof AdminSupervisionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJuryRoute: AdminJuryRoute,
  AdminMissionsRoute: AdminMissionsRoute,
  AdminRelevesRoute: AdminRelevesRoute,
  AdminRunRoute: AdminRunRoute,
  AdminSupervisionRoute: AdminSupervisionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BaremeRoute: BaremeRoute,
  CodexRoute: CodexRoute,
  ConnexionRoute: ConnexionRoute,
  LoreRoute: LoreRoute,
  PhotoRoute: PhotoRoute,
  QuetesRoute: QuetesRoute,
  SimulateurRoute: SimulateurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
